# -*- coding: utf-8 -*-
{
    'name': 'CG-MOBILE APP',
    'summary': '',
    'category': 'Application',
    'version': '17.0',
    'sequence': -100,
    'author': 'Irokoo | Lilian Olivier',
    'license': 'AGPL-3',
    'website': 'https://www.irokoo.fr',
    'description': '',
    'depends': [
        'cgm_i18n',
        'cgm_sale',
        'cgm_stock',
        'cgm_account',
        'cgm_contacts',
        'cgmobile',
        'common_connector_library',
        'shopify_ept',
        'stock_picking_return_refund_option',
    ],
    'data': [],
    'application': True,
    'installable': True,
    'auto_install': False,
}
