# -*- coding: utf-8 -*-
from . import ir_actions_report
from . import stock_picking
from . import amazon_account
from . import amazon_marketplace
from . import stock_move_line
from . import purchase_receipt
from . import purchase_order_line
from . import purchase_order
from . import device_type
from . import device_model
from . import product_color
from . import product_category
from . import product_sub_category
from . import product_material
from . import product_protection_level
from . import product_collection
from . import product_template
from . import product
from . import sale_order
from . import sale_order_line
from . import account_move_line
from . import stock_move
from . import res_partner
from . import ice_mobility
from . import sales_team